const STORAGE_KEY = "northstar-leave-state";
const leaveCatalog = { annual: { label: "Annual leave", allowance: 20 }, sick: { label: "Sick leave", allowance: 10 }, casual: { label: "Casual leave", allowance: 8 }, maternity: { label: "Maternity leave", allowance: 90 }, paternity: { label: "Paternity leave", allowance: 5 }, unpaid: { label: "Unpaid leave", allowance: null } };
const initialState = { employee: { id: "NS-1048", name: "Alex Morgan", role: "Product Designer", department: "Design", leaveBalance: { annual: 14, sick: 8, casual: 5, maternity: 90, paternity: 5, unpaid: 0 } }, leaves: [ { id: "LV-24018", type: "annual", startDate: "2024-06-24", endDate: "2024-06-26", days: 3, reason: "A short break to recharge.", status: "approved", appliedOn: "2024-06-03", handover: "Jamie Lee", timeOption: "full" }, { id: "LV-24012", type: "casual", startDate: "2024-06-14", endDate: "2024-06-14", days: 1, reason: "Personal appointment.", status: "pending", appliedOn: "2024-06-10", handover: "Priya Shah", timeOption: "full" }, { id: "LV-24004", type: "sick", startDate: "2024-05-20", endDate: "2024-05-20", days: 1, reason: "Not feeling well.", status: "approved", appliedOn: "2024-05-20", handover: "Marcus Chen", timeOption: "full" }, { id: "LV-23988", type: "annual", startDate: "2024-04-02", endDate: "2024-04-05", days: 4, reason: "Family visit.", status: "rejected", appliedOn: "2024-03-15", handover: "Sofia Alvarez", timeOption: "full" } ], teamLeaves: [ { employee: "Jamie Lee", type: "annual", startDate: "2024-06-17", endDate: "2024-06-21", status: "approved" }, { employee: "Priya Shah", type: "annual", startDate: "2024-06-24", endDate: "2024-06-26", status: "approved" }, { employee: "Marcus Chen", type: "sick", startDate: "2024-06-14", endDate: "2024-06-14", status: "pending" }, { employee: "Sofia Alvarez", type: "casual", startDate: "2024-06-28", endDate: "2024-06-28", status: "approved" } ] };
let state = loadState();
let calendarDate = new Date(2024, 5, 1);
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

function clone(value) { return JSON.parse(JSON.stringify(value)); }
function loadState() { try { const saved = localStorage.getItem(STORAGE_KEY); return saved ? { ...clone(initialState), ...JSON.parse(saved) } : clone(initialState); } catch { return clone(initialState); } }
function saveToLocalStorage(showMessage = false) { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); if (showMessage) showToast("Workspace saved locally"); }
function formatDate(dateString, options = { month: "short", day: "numeric", year: "numeric" }) { if (!dateString) return "-"; return new Intl.DateTimeFormat("en-US", options).format(new Date(`${dateString}T12:00:00`)); }
function formatRange(leave) { const start = formatDate(leave.startDate, { month: "short", day: "numeric" }); const end = formatDate(leave.endDate, { month: "short", day: "numeric", year: "numeric" }); return `${start} - ${end}`; }
function calculateWorkingDays(start, end) { if (!start || !end) return 0; const current = new Date(`${start}T12:00:00`); const finish = new Date(`${end}T12:00:00`); if (finish < current) return 0; let days = 0; while (current <= finish) { const weekday = current.getDay(); if (weekday !== 0 && weekday !== 6) days++; current.setDate(current.getDate() + 1); } return days; }
function getConsumed(type) { return state.leaves.filter(leave => leave.type === type && leave.status === "approved").reduce((total, leave) => total + leave.days, 0); }
function getRemaining(type) { const balance = state.employee.leaveBalance[type]; return balance == null ? null : Math.max(0, balance); }
function statusBadge(status) { return `<span class="status-badge badge-${status}">${status[0].toUpperCase() + status.slice(1)}</span>`; }
function renderDashboard() { const pending = state.leaves.filter(leave => leave.status === "pending").length; $("#dashboardStats").innerHTML = [ ["Annual leave", getRemaining("annual"), "days remaining"], ["Sick leave", getRemaining("sick"), "days remaining"], ["Casual leave", getRemaining("casual"), "days remaining"], ["Pending requests", pending, pending === 1 ? "request awaiting review" : "requests awaiting review"] ].map(([label, number, sub]) => `<article class="stat-card"><span class="stat-label">${label}</span><div class="stat-number">${number}</div><span class="stat-sub">${sub}</span></article>`).join(""); $("#recentRequests").innerHTML = state.leaves.slice(0, 3).map(leave => `<tr><td class="type-cell">${leaveCatalog[leave.type].label}</td><td class="date-cell">${formatRange(leave)}</td><td>${leave.days}</td><td>${statusBadge(leave.status)}</td></tr>`).join(""); $("#balanceList").innerHTML = ["annual", "sick", "casual"].map(type => { const remaining = getRemaining(type); const used = getConsumed(type); const percentage = Math.min(100, (used / leaveCatalog[type].allowance) * 100); return `<div class="balance-row"><span class="balance-label">${leaveCatalog[type].label}</span><span class="balance-value">${remaining} days</span><div class="progress"><span style="width:${percentage}%"></span></div></div>`; }).join(""); }
function renderHistory() { const type = $("#historyType").value; const status = $("#historyStatus").value; const filtered = state.leaves.filter(leave => (type === "all" || leave.type === type) && (status === "all" || leave.status === status)); $("#historyCount").textContent = `${filtered.length} request${filtered.length === 1 ? "" : "s"}`; $("#historyRows").innerHTML = filtered.length ? filtered.map(leave => `<tr><td class="type-cell">${leave.id}</td><td>${leaveCatalog[leave.type].label}</td><td class="date-cell">${formatRange(leave)}</td><td>${leave.days}</td><td>${statusBadge(leave.status)}</td><td class="date-cell">${formatDate(leave.appliedOn)}</td><td>${leave.status === "pending" ? `<button class="text-button cancel-action" data-id="${leave.id}" type="button">Cancel</button>` : `<button class="text-button view-action" data-id="${leave.id}" type="button">View</button>`}</td></tr>`).join("") : `<tr><td colspan="7" class="empty-state">No requests match these filters.</td></tr>`; }
function updateFormPreview() { const type = $("#leaveType").value; const remaining = getRemaining(type); $("#balancePreview").textContent = remaining == null ? "No balance limit for unpaid leave" : `${remaining} days available`; const days = calculateWorkingDays($("#startDate").value, $("#endDate").value); const timeOption = $("#timeOption").value; const adjusted = timeOption === "full" ? days : days ? days - .5 : 0; $("#dayCalculation").innerHTML = `<span class="calculation-icon">${days ? "✓" : "-"}</span><div><strong>${adjusted} working day${adjusted === 1 ? "" : "s"}</strong><span>${days ? "Weekends are excluded automatically" : "Select your dates to calculate duration"}</span></div>`; }
function renderCalendar() { const year = calendarDate.getFullYear(); const month = calendarDate.getMonth(); $("#calendarMonth").textContent = new Intl.DateTimeFormat("en-US", { month: "long", year: "numeric" }).format(calendarDate); const firstDay = new Date(year, month, 1).getDay(); const mondayOffset = (firstDay + 6) % 7; const daysInMonth = new Date(year, month + 1, 0).getDate(); const previousDays = new Date(year, month, 0).getDate(); const cells = []; for (let index = 0; index < 42; index++) { const dayNumber = index - mondayOffset + 1; const date = dayNumber < 1 ? new Date(year, month - 1, previousDays + dayNumber) : dayNumber > daysInMonth ? new Date(year, month + 1, dayNumber - daysInMonth) : new Date(year, month, dayNumber); const isCurrentMonth = date.getMonth() === month; const dateKey = date.toISOString().slice(0, 10); const leaves = [...state.teamLeaves, ...state.leaves.map(leave => ({ ...leave, employee: "You" }))].filter(leave => dateKey >= leave.startDate && dateKey <= leave.endDate); const today = dateKey === "2024-06-19"; cells.push(`<div class="calendar-day ${isCurrentMonth ? "" : "muted"} ${date.getDay() === 0 || date.getDay() === 6 ? "weekend" : ""} ${today ? "today" : ""}"><span class="day-number">${date.getDate()}</span>${leaves.slice(0, 2).map(leave => `<button class="calendar-leave ${leave.status === "pending" ? "pending" : ""}" data-date="${dateKey}" type="button"><i></i>${leave.employee}</button>`).join("")}</div>`); } $("#calendarGrid").innerHTML = cells.join(""); }
function showCalendarDetails(dateKey) { const leaves = [...state.teamLeaves, ...state.leaves.map(leave => ({ ...leave, employee: "You" }))].filter(leave => dateKey >= leave.startDate && dateKey <= leave.endDate); const details = $("#calendarDetails"); if (!leaves.length) { details.classList.add("hidden"); return; } details.classList.remove("hidden"); details.innerHTML = `<h3>People out on ${formatDate(dateKey, { weekday: "long", month: "long", day: "numeric" })}</h3>${leaves.map(leave => `<div class="calendar-detail-item"><span><strong>${leave.employee}</strong> &middot; ${leaveCatalog[leave.type].label}</span>${statusBadge(leave.status)}</div>`).join("")}`; }
function showTab(tab) { $$(".tab-panel").forEach(panel => panel.classList.toggle("active", panel.id === `${tab}Panel`)); $$(".nav-item").forEach(button => button.classList.toggle("active", button.dataset.tab === tab)); $("#pageLabel").textContent = { dashboard: "Overview", apply: "Apply for leave", history: "Leave history", calendar: "Team calendar" }[tab]; $(".sidebar").classList.remove("open"); if (tab === "dashboard") renderDashboard(); if (tab === "history") renderHistory(); if (tab === "calendar") renderCalendar(); }
function showToast(message) { const toast = $("#toast"); toast.textContent = message; toast.classList.add("show"); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove("show"), 3200); }
function openModal(content) { $("#modalContent").innerHTML = content; $("#modal").classList.remove("hidden"); $("#closeModal").focus(); }
function closeModal() { $("#modal").classList.add("hidden"); }
function submitLeave(event) { event.preventDefault(); const type = $("#leaveType").value; const startDate = $("#startDate").value; const endDate = $("#endDate").value; const reason = $("#reason").value.trim(); const handover = $("#handover").value; const timeOption = $("#timeOption").value; const error = $("#formError"); const days = calculateWorkingDays(startDate, endDate); const adjustedDays = timeOption === "full" ? days : days ? days - .5 : 0; const overlapping = state.leaves.some(leave => leave.status === "approved" && startDate <= leave.endDate && endDate >= leave.startDate); error.textContent = ""; if (!startDate || !endDate || endDate < startDate) return error.textContent = "Choose a valid date range where the end date is after the start date."; if (!days) return error.textContent = "Your selected range contains no working days."; if (reason.length < 10) return error.textContent = "Please provide at least 10 characters for your reason."; if (!handover) return error.textContent = "Select a teammate for the handover."; const remaining = getRemaining(type); if (remaining != null && adjustedDays > remaining) return error.textContent = `This request exceeds your ${leaveCatalog[type].label.toLowerCase()} balance.`; if (overlapping && !window.confirm("These dates overlap with an existing approved leave. Submit anyway?")) return; const id = `LV-${String(Date.now()).slice(-5)}`; state.leaves.unshift({ id, type, startDate, endDate, days: adjustedDays, reason, status: "pending", appliedOn: new Date().toISOString().slice(0, 10), handover, timeOption }); saveToLocalStorage(); $("#leaveForm").reset(); updateFormPreview(); renderDashboard(); showTab("history"); showToast("Leave request submitted for review"); }
function cancelLeave(id) { const leave = state.leaves.find(item => item.id === id); if (!leave) return; openModal(`<h2 id="modalTitle">Cancel this request?</h2><p>Your ${leaveCatalog[leave.type].label.toLowerCase()} request for ${formatRange(leave)} will be marked as cancelled.</p><div class="modal-actions"><button class="button button-secondary" id="dismissModal" type="button">Keep request</button><button class="button button-primary" id="confirmCancel" type="button">Cancel request</button></div>`); $("#dismissModal").onclick = closeModal; $("#confirmCancel").onclick = () => { leave.status = "cancelled"; saveToLocalStorage(); closeModal(); renderHistory(); renderDashboard(); showToast("Request cancelled"); }; }
function exportCSV() { const headers = ["Reference", "Leave type", "Start date", "End date", "Days", "Status", "Applied on"]; const rows = state.leaves.map(leave => [leave.id, leaveCatalog[leave.type].label, leave.startDate, leave.endDate, leave.days, leave.status, leave.appliedOn]); const csv = [headers, ...rows].map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "northstar-leave-history.csv"; link.click(); URL.revokeObjectURL(link.href); showToast("Leave history exported"); }

$("#loginForm").addEventListener("submit", event => { event.preventDefault(); $("#loginView").classList.add("hidden"); $("#appView").classList.remove("hidden"); showTab("dashboard"); showToast("Welcome back, Alex"); });
$("#logoutButton").addEventListener("click", () => { $("#appView").classList.add("hidden"); $("#loginView").classList.remove("hidden"); });
$("#openSidebar").addEventListener("click", () => $(".sidebar").classList.add("open")); $("#closeSidebar").addEventListener("click", () => $(".sidebar").classList.remove("open"));
$$('[data-tab]').forEach(button => button.addEventListener("click", () => showTab(button.dataset.tab)));
["#leaveType", "#startDate", "#endDate", "#timeOption"].forEach(selector => $(selector).addEventListener("change", updateFormPreview));
$("#leaveForm").addEventListener("submit", submitLeave); $("#historyType").addEventListener("change", renderHistory); $("#historyStatus").addEventListener("change", renderHistory); $("#exportButton").addEventListener("click", exportCSV);
$("#historyRows").addEventListener("click", event => { const button = event.target.closest("button"); if (!button) return; const leave = state.leaves.find(item => item.id === button.dataset.id); if (button.classList.contains("cancel-action")) cancelLeave(button.dataset.id); if (button.classList.contains("view-action") && leave) openModal(`<h2 id="modalTitle">${leaveCatalog[leave.type].label}</h2><p>${formatRange(leave)} &middot; ${leave.days} day${leave.days === 1 ? "" : "s"}</p><p>${leave.reason}</p><div class="modal-actions"><button class="button button-primary" id="dismissModal" type="button">Done</button></div>`); $("#dismissModal")?.addEventListener("click", closeModal); });
$("#calendarGrid").addEventListener("click", event => { const leave = event.target.closest(".calendar-leave"); if (leave) showCalendarDetails(leave.dataset.date); }); $("#previousMonth").addEventListener("click", () => { calendarDate.setMonth(calendarDate.getMonth() - 1); renderCalendar(); }); $("#nextMonth").addEventListener("click", () => { calendarDate.setMonth(calendarDate.getMonth() + 1); renderCalendar(); }); $("#todayButton").addEventListener("click", () => { calendarDate = new Date(2024, 5, 1); renderCalendar(); }); $("#closeModal").addEventListener("click", closeModal); $("#modal").addEventListener("click", event => { if (event.target.id === "modal") closeModal(); }); $("#notificationButton").addEventListener("click", () => showToast("You are all caught up"));
setInterval(() => saveToLocalStorage(), 30000); updateFormPreview();
